version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fullstack
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3308:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  products-service:
    build: ./products-service
    container_name: products_service
    restart: always
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpass
      DATABASE_NAME: fullstack
      API_KEY: secret-products-123
    command: npm run start:prod
  inventory-service:
    build: ./inventory-service
    container_name: inventory_service
    restart: always
    depends_on:
      - mysql
      - products-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpass
      DATABASE_NAME: fullstack
      PRODUCTS_API_URL: http://products-service:3001
      API_KEY: secret-inventory-456
    command: npm run start:prod
volumes:
  mysql_data: